### ISSUE TITLE
Infinite lapis and sulfur

### ISSUE THREAD

**Issue by skykuma** [AnodeCathode/TechNodeFirmaCraft#116]
Take 1 lapis ore.
Grind in the IE crusher to get 10 powder.
Melt the powder in NC melter, then the ingot former.
End up with 10 lapis from 1.
Repeat for infinite lapis.

Same with sulfur except it's 9 instead of 10. 

The issue is that 1 ore and 1 powder creates the same amount of liquid (in this case 666mb) in the NC melter.

I guess it doesn't have to be the IE crusher. As long as you get more powder than starting ore amount.

**Comment by AnodeCathode** [comment]
Thanks for the heads up. F(&( NC Melter. Fixed in 12.2.48
