### ISSUE TITLE
Unable to produce flux from flux rocks in IE crusher

### ISSUE THREAD

**Issue by skykuma** [AnodeCathode/TechNodeFirmaCraft#117]
1. JEI only lists dolomite as a recipe in the IE crusher while the BWM mill, TFC quern, and Horsepower grindstone has all the flux rocktypes showing.

2. When actually inserting flux rocks into the crusher, nothing happens and the rocks just sit there.

**Comment by AnodeCathode** [comment]
Fixed in next version
