### ISSUE TITLE
Small block breaker and small tree breaker (engineer's decor mod) has exact same recipe 

### ISSUE THREAD

**Issue by skykuma** [AnodeCathode/TechNodeFirmaCraft#121]

**Comment by AnodeCathode** [comment]
Pretty sure they don't

**Comment by skykuma** [comment]
![Block Breaker](https://user-images.githubusercontent.com/74868023/100694294-a2145900-3343-11eb-854c-be2d39bc1dbe.png)
![Tree Cutter](https://user-images.githubusercontent.com/74868023/100694297-a3458600-3343-11eb-9cd7-734399e826c3.png)

The axes cycle through various ingots but the crafting recipe always defaults to the block breaker in a crafting table. 
The mechanical component is steel in both cases and so are the plates.

technodefirmacraft v12.2.47

**Comment by AnodeCathode** [comment]
Ah, I see the issue. Not with the recipe but with the oredict entry for the pick. Fixed in next version.
