### ISSUE TITLE
Disappear AR Space Station Container in Satellite Bay after loading

### ISSUE THREAD

**Issue by ViachaclauSlepau** [AnodeCathode/TechNodeFirmaCraft#122]
After the launch of the rocket, the station is not created.

**Comment by AnodeCathode** [comment]
>When you make a space station, make copies of the station id chip. If you for some reason lose your only chip and can't get back to the station with a space elevator, the station is lost<


There is a reason this is in the TNFC Manual.

**Comment by ViachaclauSlepau** [comment]
Disappear AR Space Station Container! I have copies of the station id chip, but after the launch of the rocket, the station is not created.
