### ISSUE TITLE
IE excavator mineral deposit doesn't have the labeled vein

### ISSUE THREAD

**Issue by skykuma** [AnodeCathode/TechNodeFirmaCraft#125]
The IE excavator manual (mineral deposit section):

Boron deposit only has gems available (also seems redundant to have if there is a borax deposit)
Chromite and Magnesite deposit also has the exact same gems available.

So boron can be excavated in a borax deposit but chromite and magnesite are unavailable? 
If so, maybe remove entries in the IE manual (and the redundant boron page)? 
Or is this intended? 

Playing on a server running technode v12.2.42
No magnesite from IE magnesite vein

not tested latest v12.2.50.1 with excavator but the manual is as claimed.

Thanks for the hard work! Really appreciate the time and effort you guys put into this!

**Comment by AnodeCathode** [comment]
Yeah I need to fix that. There used to be a dedicated boron. But it got nuked and I neglected to update that. Thanks.

**Comment by AnodeCathode** [comment]
Fixed up in 12.2.51
