### ISSUE TITLE
Unable to create the coke oven from immersive engineering.

### ISSUE THREAD

**Issue by AidiaPlanewalker** [AnodeCathode/TechNodeFirmaCraft#132]
The recipe for coke oven bricks includes pig iron screws (and the rods/bolts needed to craft the screws) and strips from TFCTech. I believe these were hidden with the 12.2.55 change "- Hide a lot of the unused TFCTech wires/gears etc", thus causing the coke oven to be uncreatable and blocking any path to make coal coke.

Edit: image attached
![image](https://user-images.githubusercontent.com/60332347/104154964-21219600-53b4-11eb-9a36-ceaf803db8bd.png)

**Comment by AnodeCathode** [comment]
Hotfixed
