### ISSUE TITLE
IE Cooling Tower should process NC Exhaust Steam

### ISSUE THREAD

**Issue by Broam** [AnodeCathode/TechNodeFirmaCraft#136]
It'd be really nice to make a 'loop' instead of having to bin the water out of the turbine. If the cooling tower outputs fresh water, I can turn rainwater into fresh water. There is a "preheated" water that NC reactors can use.

**Comment by AnodeCathode** [comment]
Fixed in 12.2.64 - Turbine now outputs exhaust steam which can be cooled with either fresh water or distilled water to get the same back out.
