### ISSUE TITLE
Extreme lag spikes every second

### ISSUE THREAD

**Issue by bitsbytes123** [AnodeCathode/TechNodeFirmaCraft#138]
Every second the frametime appears to spike and then recover, which causes extremely annoying lag when trying to play the pack. From looking at the piechart there is an "unspecified" process consuming a lot of memory and then giving it back every second, this would be the cause of the issue but I can't figure out which mod is lagging the game. [video showing frametimes](https://www.youtube.com/watch?v=xX_J8ugUwFo)

**Comment by AnodeCathode** [comment]
No idea. Not enough information to even make a guess. However because you've added Optifine and who knows what else, really don't know how I can support.

**Comment by bitsbytes123** [comment]
Issue occurred on a brand new install before adding anything.
