### ISSUE TITLE
RH Precipitation Chamber conflict with Flue Gas

### ISSUE THREAD

**Issue by Tearloch** [AnodeCathode/TechNodeFirmaCraft#146]
The recipe for Potassium Carbonate can only be crafted by either using water_minecraft or Flue Gas in a precipitation chamber. Since water_minecraft doesn't exist in TFC, flue gas is required, however the precipitation chamber does not accept any kind of gas as an input and flue gas is, well, a gas.

Possible solution could be to create a liquid form of flue gas via the condenser, or just to change the potassium carbonate recipe and flue gas use all together

**Comment by AnodeCathode** [comment]
Well actually minecraft (vanilla) water does exist in TNFC. It's called Rain Water. You can obtain it with the evaporation tank or the rain tank.

**Comment by Tearloch** [comment]
Ahh I see. I added the Weather2 mod to add storms and such, but didnt realize that the rain from that mod wouldnt register with the tanks to fill them up. After removing that mod I can now fill those tanks up.
