### ISSUE TITLE
Cannot /kill myself

### ISSUE THREAD

**Issue by Topulca** [AnodeCathode/TechNodeFirmaCraft#161]
The fix is to delete the "FirstAid" mod, but it is not in the "mods" folder.

**Comment by agilmore2** [comment]
The other fix is to nbtedit your player health to 0. The loading tips say don't use /kill. This is why.

**Comment by Gaelmare** [comment]
Unfortunately, we have no permanent fix to this issue. Workaround is to not use /kill, and NBTEdit the player after it has occurred.
