### ISSUE TITLE
TFC bronze ingots produce incorrect dusts

### ISSUE THREAD

**Issue by HumanWho** [AnodeCathode/TechNodeFirmaCraft#7]
I play TechNodeFirmaCraft on the latest update for 1..12.2. When putting ingots into the crusher machine, Bismuth bronze ingots give Black Bronze dust, and Black Bronze ingots produce Bismuth Bronze dust, seemingly the outputs are swapped.

**Comment by AnodeCathode** [comment]
Okay I'll look and sort it. Thanks for the info

**Comment by HumanWho** [comment]
> Okay I'll look and sort it. Thanks for the info

Great! Thank you for such a great mudpack as well!

**Comment by AnodeCathode** [comment]
Resolved in 12.2.23
