### ISSUE TITLE
Cannot work on anvil with Tungsten steel.

### ISSUE THREAD

**Issue by ViachaclauSlepau** [AnodeCathode/TechNodeFirmaCraft#79]
Cannot work on anvil with Tungsten steel. When heated, it does not show Work-Weld-Dangerous

**Comment by AnodeCathode** [comment]
You're not heating it enough. It's a very high end Steel that requires special handling. Use coke coal or thermite and lots of bellows. Or use a Metal Press. 

Working as intended

**Comment by ViachaclauSlepau** [comment]
http://prntscr.com/vh7j3z now work! Pls HELP!
